### ISSUE TITLE
create from compose file

### ISSUE THREAD

**Issue by prapdm** [tpbowden/swarm-ingress-router#32]
Docker Swarm 1.13 has new future (https://blog.docker.com/2017/01/whats-new-in-docker-1-13/)
I'm trying to use compose-files to deploy service:

ngnix.yml
```
version: '3'
services:
  web:
    image: nginx:stable-alpine
    labels:
      - "ingress=true"
      - "ingress.dnsname=somedomain.com"
      - "ingress.targetport=80"
    networks:
      - outside
networks:
  outside:
    external:
      name: frontends
```

`docker stack deploy --compose-file=ngnix.yml test`

After visiting somedomain.com my browser show me: Failed to look up service
But if I run service in traditional way everything is working:

```
 docker service create --name frontend --label ingress=true --label ingress.dnsname=somedomain.com \
  --label ingress.targetport=80 --network frontends nginx:stable-alpine
```

**Comment by tpbowden** [comment]
Haven't looked into using compose yet but I'm keen to add support for deploying everything as a swarm stack. Last I looked there was an issue mounting directories with compose but I'll have another look when i get time

**Comment by ernest-okot** [comment]
Same here... fails to look up service. Here are my compose files

Router Stack

```
version: '3'

services:
  backend:
    image: redis:3.2-alpine
    networks:
      - default

  collector:
    image: tpbowden/swarm-ingress-router:latest
    command: -r backend:6379 collector
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  router:
    image: tpbowden/swarm-ingress-router:latest
    command: -r backend:6379 server -b 0.0.0.0
    networks:
      - default
      - proxy
    ports:
      - 80:8080
      - 443:8443

networks:
  default:
    driver: overlay
  proxy:
    external: true
```

Demo stack

```
version: '3'

services:
  nginx:
    image: nginx:alpine
    labels:
      ingress: 'true'
      ingress.dnsname: demo.local
      ingress.targetport: 80
    networks:
      - proxy

networks:
  proxy:
    external: true
```

Networks
```
NETWORK ID          NAME                DRIVER              SCOPE
...
ourdrp1radxn        proxy               overlay             swarm
```

**Comment by tpbowden** [comment]
I'm currently looking into this, for some reason the backend collector isn't detecting the frontend service using the unix socket API, I'll keep you updated.

**Comment by tpbowden** [comment]
Ok I've managed to get it to work. The problem is that you're assigning the labels to containers rather than the service itself. They need to put placed under the `deploy` key to be created correctly. Here's my working stack:

```yaml

version: "3"

services:
  router-storage:
    image: redis:3.2-alpine
    networks:
      - router-management

  router-backend:
    image: tpbowden/swarm-ingress-router
    networks:
      - router-management
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -r router-storage:6379 collector

  router:
    image: tpbowden/swarm-ingress-router
    command: -r router-storage:6379 server -b 0.0.0.0
    ports:
      - 80:8080
      - 443:8443
    networks:
      - router-management
      - frontends

  frontend:
    image: nginx:stable-alpine
    networks:
      - frontends
    deploy:
      labels:
        ingress: "true"
        ingress.dnsname: localhost
        ingress.targetport: 80




networks:
  router-management:
  frontends:

```

**Comment by ernest-okot** [comment]
Thanks for the help, perhaps we should add this to the readme

**Comment by tpbowden** [comment]
Yeah I'll add the file to the repo and some docs

**Comment by ernest-okot** [comment]
Hello @tpbowden, I just ran into another issue related to using docker-compose. How would one enable ssl for a service started from a compose file? Because the implementation relies on "deploy labels", the value `$(cat example.com.crt)` cannot be resolved in a docker-compose file.
```yaml
# docker-compose.yml

version: "3"

services:
  router-storage:
    image: redis:3.2-alpine
    networks:
      - router-management

  router-backend:
    image: tpbowden/swarm-ingress-router
    networks:
      - router-management
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -r router-storage:6379 collector

  router:
    image: tpbowden/swarm-ingress-router
    command: -r router-storage:6379 server -b 0.0.0.0
    ports:
      - 80:8080
      - 443:8443
    networks:
      - router-management
      - frontends

  frontend:
    image: nginx:stable-alpine
    networks:
      - frontends
    deploy:
      labels:
        ingress: "true"
        ingress.dnsname: example.local
        ingress.targetport: 80
        ingress.tls=true
        ingress.cert="$(cat <your cert file>)"
        ingress.key="$(cat <your key file>)"


networks:
  router-management:
  frontends:
```
I've tried to look around for possible work arounds with no luck, any ideas :thinking:
